# -*- coding: utf-8 -*-
"""bmed_functions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O1KZyEJ5CiYbvROdt16SbwTWXW8KqkRs
"""

import numpy as np
import pandas as pd

def split_with_all_anomalies_in_test(X, y, test_size=0.2, random_state=42):
    """
    Split data ensuring all anomaly samples are in the test set.

    Parameters
    ----------
    X : array-like or DataFrame
        Feature data.
    y : array-like
        Labels (binary: 0 and 1).
        Class 1 represents the anomaly class.
        Class 0 represents the normal class.
    test_size : float, default=0.2
        Desired proportion of test set (approximate).
    random_state : int, default=42
        Random seed.

    Returns
    -------
    X_train, X_test, y_train, y_test
    """
    X = np.array(X)
    y = np.array(y)

    rng = np.random.default_rng(random_state)

    # Indices of each class
    class1_idx = np.where(y == 1)[0]
    class0_idx = np.where(y == 0)[0]

    # All class 1 goes to test set
    test_idx = list(class1_idx)

    # Desired total test size
    n_total = len(y)
    desired_test_size = int(np.ceil(test_size * n_total))

    # Remaining slots for class 0 in test set
    remaining = max(0, desired_test_size - len(class1_idx))

    # Shuffle class 0 indices
    shuffled_class0 = rng.permutation(class0_idx)

    # Add some class 0 samples to test set
    test_idx.extend(shuffled_class0[:remaining])

    # Remaining class 0 go to train
    train_idx = shuffled_class0[remaining:]

    # Convert to arrays
    test_idx = np.array(test_idx)
    train_idx = np.array(train_idx)

    # Extract splits
    X_train, X_test = X[train_idx], X[test_idx]
    y_train, y_test = y[train_idx], y[test_idx]

    return X_train, X_test, y_train, y_test

# Example

X = np.arange(20)
y = np.array([0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0])

X_train, X_test, y_train, y_test = split_with_all_anomalies_in_test(X, y)

print("y_train:", y_train)
print("y_test:", y_test)

